server:
  port: 8080

#需要获取自己的appid和secret填到下面
appid:
secret:
grant_type: authorization_code

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/orderingsys?serverTimezone=GMT%2B8&useSSL=true
    username: root
    password:
mybatis:
  mapper-locations: classpath:mapping/*.xml