server:
    port: 8080


appid: wxbc8520219ca144f4
secret: 8afbc946b865bbebee2ee1068c6d0a29
grant_type: authorization_code

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/orderingsys?serverTimezone=GMT%2B8&useSSL=true
    username: root
    password: runrun123

mybatis:
  mapper-locations: classpath:mapping/*.xml