server:
    port:8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/orderingsys?serverTimezone=GMT%2B8&useSSL=true
    username: root
    password: runrun123

mybatis:
  mapper-locations: classpath:mapping/*.xml